/**
 * Auto-generated API sidebar configuration.
 * Generated by scripts/generate-api-docs.ts
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * This file uses the default API version (v0.0.1-rc30 → v001-rc30) for sidebar links.
 * The Sidebar.astro component dynamically rewrites these links based on
 * the current URL's version, so users see version-appropriate links.
 */

import type { StarlightUserConfig } from '@astrojs/starlight/types';

type SidebarItem = NonNullable<StarlightUserConfig['sidebar']>[number];

export const apiSidebarConfig: SidebarItem[] = [
  { label: 'Overview', slug: 'api/v001-rc30' },
  {
    label: 'Sprites',
    collapsed: true,
    items: [
      {
        label: 'Create Sprite',
        link: '/api/v001-rc30/sprites#create-sprite',
        attrs: { 'data-method': 'post' },
      },
      {
        label: 'List Sprites',
        link: '/api/v001-rc30/sprites#list-sprites',
        attrs: { 'data-method': 'get' },
      },
      {
        label: 'Get Sprite',
        link: '/api/v001-rc30/sprites#get-sprite',
        attrs: { 'data-method': 'get' },
      },
      {
        label: 'Update Sprite',
        link: '/api/v001-rc30/sprites#update-sprite',
        attrs: { 'data-method': 'put' },
      },
      {
        label: 'Delete Sprite',
        link: '/api/v001-rc30/sprites#delete-sprite',
        attrs: { 'data-method': 'delete' },
      },
    ],
  },
  {
    label: 'Checkpoints',
    collapsed: true,
    items: [
      {
        label: 'Create Checkpoint',
        link: '/api/v001-rc30/checkpoints#create-checkpoint',
        attrs: { 'data-method': 'post' },
      },
      {
        label: 'List Checkpoints',
        link: '/api/v001-rc30/checkpoints#list-checkpoints',
        attrs: { 'data-method': 'get' },
      },
      {
        label: 'Get Checkpoint',
        link: '/api/v001-rc30/checkpoints#get-checkpoint',
        attrs: { 'data-method': 'get' },
      },
      {
        label: 'Restore Checkpoint',
        link: '/api/v001-rc30/checkpoints#restore-checkpoint',
        attrs: { 'data-method': 'post' },
      },
    ],
  },
  {
    label: 'Exec',
    collapsed: true,
    items: [
      {
        label: 'Execute Command',
        link: '/api/v001-rc30/exec#execute-command',
        attrs: { 'data-method': 'wss' },
      },
      {
        label: 'List Exec Sessions',
        link: '/api/v001-rc30/exec#list-exec-sessions',
        attrs: { 'data-method': 'get' },
      },
      {
        label: 'Execute Command',
        link: '/api/v001-rc30/exec#execute-command',
        attrs: { 'data-method': 'post' },
      },
      {
        label: 'Attach to Exec Session',
        link: '/api/v001-rc30/exec#attach-to-exec-session',
        attrs: { 'data-method': 'wss' },
      },
      {
        label: 'Kill Exec Session',
        link: '/api/v001-rc30/exec#kill-exec-session',
        attrs: { 'data-method': 'post' },
      },
    ],
  },
  {
    label: 'Filesystem',
    collapsed: true,
    items: [
      {
        label: 'Read File',
        link: '/api/v001-rc30/filesystem#read-file',
        attrs: { 'data-method': 'get' },
      },
      {
        label: 'Write File',
        link: '/api/v001-rc30/filesystem#write-file',
        attrs: { 'data-method': 'put' },
      },
      {
        label: 'List Directory',
        link: '/api/v001-rc30/filesystem#list-directory',
        attrs: { 'data-method': 'get' },
      },
      {
        label: 'Delete File or Directory',
        link: '/api/v001-rc30/filesystem#delete-file-or-directory',
        attrs: { 'data-method': 'delete' },
      },
      {
        label: 'Rename File or Directory',
        link: '/api/v001-rc30/filesystem#rename-file-or-directory',
        attrs: { 'data-method': 'post' },
      },
      {
        label: 'Copy File or Directory',
        link: '/api/v001-rc30/filesystem#copy-file-or-directory',
        attrs: { 'data-method': 'post' },
      },
      {
        label: 'Change File Mode',
        link: '/api/v001-rc30/filesystem#change-file-mode',
        attrs: { 'data-method': 'post' },
      },
      {
        label: 'Change File Owner',
        link: '/api/v001-rc30/filesystem#change-file-owner',
        attrs: { 'data-method': 'post' },
      },
      {
        label: 'Watch Filesystem',
        link: '/api/v001-rc30/filesystem#watch-filesystem',
        attrs: { 'data-method': 'wss' },
      },
    ],
  },
  {
    label: 'Policy',
    collapsed: true,
    items: [
      {
        label: 'Get Network Policy',
        link: '/api/v001-rc30/policy#get-network-policy',
        attrs: { 'data-method': 'get' },
      },
      {
        label: 'Set Network Policy',
        link: '/api/v001-rc30/policy#set-network-policy',
        attrs: { 'data-method': 'post' },
      },
    ],
  },
  {
    label: 'HTTP Proxy',
    collapsed: true,
    items: [
      {
        label: 'TCP Proxy',
        link: '/api/v001-rc30/proxy#tcp-proxy',
        attrs: { 'data-method': 'wss' },
      },
    ],
  },
  {
    label: 'Services',
    collapsed: true,
    items: [
      {
        label: 'List Services',
        link: '/api/v001-rc30/services#list-services',
        attrs: { 'data-method': 'get' },
      },
      {
        label: 'Get Service',
        link: '/api/v001-rc30/services#get-service',
        attrs: { 'data-method': 'get' },
      },
      {
        label: 'Create Service',
        link: '/api/v001-rc30/services#create-service',
        attrs: { 'data-method': 'put' },
      },
      {
        label: 'Start Service',
        link: '/api/v001-rc30/services#start-service',
        attrs: { 'data-method': 'post' },
      },
      {
        label: 'Stop Service',
        link: '/api/v001-rc30/services#stop-service',
        attrs: { 'data-method': 'post' },
      },
      {
        label: 'Get Service Logs',
        link: '/api/v001-rc30/services#get-service-logs',
        attrs: { 'data-method': 'get' },
      },
    ],
  },
  { label: 'Type Definitions', slug: 'api/v001-rc30/types' },
];
